version: '3'
services:
  xp-connector:
    container_name: xp-bugbot
    image: ghcr.io/xp-bot/xp-bugbot:latest
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/xp-bugbot/setup.json:/app/setup.json
    environment:
      - TOKEN=NzkzNjQ3OTM0MDg0MDg3ODA4.X-vUPA.QEq3Km3iM8e1gB9_1qnuJUH-TQs
      - GUILD=707242215579189279
      - SUPPORT_ROLE=707246903003447357
      - ARCHIVE_CATEGORY=982917649778491402
      - TICKET_CATEGORY=927934640818376745
      - GET_HELP_FORUM_CHANNEL=1159984855040405637
      - API_ACCESS=NzIxODg7QrRcneyOy6bQBxyzR4PRT68zk9Q
      - ALIAS_265849018662387712=yuki
      - ALIAS_524860237979582464=conny
      - ALIAS_650755708857483344=haxnts
      - ALIAS_481099018676600853=cringley
